dist: bionic
language: python
python:
  - "3.8"
services:
  - postgresql
before_script:
  - psql -c 'CREATE DATABASE music_bot_tests;' -U postgres
  - psql -c 'CREATE USER music_bot_user WITH password '#3!dss~&34j';' -U postgres
  - psql -c 'GRANT ALL ON DATABASE music_bot_tests TO music_bot_user;' -U postgres
env:
  PyMusicBot_SETTINGS=../test.cfg
script:
  ./tests/run_tests.sh
install:
  - pip3 install -r requirements.txt